### ISSUE TITLE
Repository as template

### ISSUE THREAD

**Issue by FredrikPAC** [patheard/aws-ecs-zitadel#2]
Hi!
Thank you for taking the time to provide this to the community.
Since there's some configuration that is specific to each user of the repo, have you considered making the repository available to be used as a template? Whit template i am reffering to https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by patheard** [comment]
Not a problem at all.  I hadn't thought of making it a template and my reluctance is that this isn't a supported repo so it'll gradually drift into a state of not working.  

I'd have no problem at all if you wanted to make a disconnected copy of the repo and create a template from it!  I think it's a good idea.

**Comment by FredrikPAC** [comment]
Great, will do! And again thank you for publishing it!

**Comment by FredrikPAC** [comment]
Here is the link to the new repo, please don't hesitate to tell if you want me to change the credits given to you at the top.  https://github.com/FredrikPAC/aws-ecs-zitadel-template

**Comment by patheard** [comment]
Honestly it looks great!  I wouldn't mind at all if you wanted to move the credits down to the bottom either but totally up to you.
